springdoc:
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    url: /v3/api-docs.yaml

spring:
  flyway:
    enabled: true

  h2:
    console:
      enabled: false

  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect