{
 "title": "Main Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Records Service",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"records-service\"} |= `mdc_X-Request-ID`"
    }
   ]
  },
  {
   "title": "Operations Service",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"operations-service\"} |= `mdc_X-Request-ID`"
    }
   ]
  },
  {
   "title": "Auth Service",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{app=\"auth-service\"} |= `mdc_X-Request-ID`"
    }
   ]
  }
 ]
}